services:
  mysql:
    image: mysql:8.4
    container_name: appstudymate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_studymate
      MYSQL_USER: studymate
      MYSQL_PASSWORD: studymate
    ports:
      - "3306:3306"
    volumes:
      - appstudymate-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  appstudymate-mysql-data: