CREATE TABLE `User` (
  `Id` VARCHAR(191) NOT NULL,
  `Name` VARCHAR(191) NOT NULL,
  `Email` VARCHAR(191) NOT NULL,
  `PasswordHash` VARCHAR(191) NOT NULL,
  `Nim` VARCHAR(191) NOT NULL,
  `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `User_Email_key`(`Email`),
  PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Schedule` (`Id` VARCHAR(191) NOT NULL, `UserId` VARCHAR(191) NOT NULL, `CourseName` VARCHAR(191) NOT NULL, `Lecturer` VARCHAR(191) NOT NULL, `Day` VARCHAR(191) NOT NULL, `StartTime` VARCHAR(191) NOT NULL, `EndTime` VARCHAR(191) NOT NULL, `Room` VARCHAR(191) NOT NULL, `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`Id`), INDEX `Schedule_UserId_Day_idx`(`UserId`, `Day`), CONSTRAINT `Schedule_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Task` (`Id` VARCHAR(191) NOT NULL, `UserId` VARCHAR(191) NOT NULL, `Title` VARCHAR(191) NOT NULL, `Description` TEXT NOT NULL, `Deadline` DATETIME(3) NOT NULL, `Status` ENUM('TODO', 'IN_PROGRESS', 'DONE') NOT NULL DEFAULT 'TODO', `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `UpdatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`Id`), INDEX `Task_UserId_Status_Deadline_idx`(`UserId`, `Status`, `Deadline`), CONSTRAINT `Task_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Note` (`Id` VARCHAR(191) NOT NULL, `UserId` VARCHAR(191) NOT NULL, `Title` VARCHAR(191) NOT NULL, `Content` TEXT NOT NULL, `RelatedTaskId` VARCHAR(191) NULL, `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `UpdatedAt` DATETIME(3) NOT NULL, PRIMARY KEY (`Id`), INDEX `Note_UserId_UpdatedAt_idx`(`UserId`, `UpdatedAt`), CONSTRAINT `Note_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `Note_RelatedTaskId_fkey` FOREIGN KEY (`RelatedTaskId`) REFERENCES `Task`(`Id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;